### ISSUE TITLE
Coffeeify imports not working in browserify

### ISSUE THREAD

**Issue by rattrayalex** [philschatz/octokat.js#10]
Hey again!

Trying this out, pretty excited. Didn't know you could do `coffee-script/register` to avoid having to compile to js, that's pretty cool. 

Unfortunately doesn't seem to be working for me =P
May be the fault of my built setup. I'm using Browserify through Watchify inside of gulp, using the Coffeeify transform. Here's the error I get when trying to `require` octocat:

```
Browserify Error { [Error: Parsing file /Users/alex/mypath/node_modules/octokat/src/octokat.coffee: Line 1: Unexpected string]
```

Again, not sure if this is on me or what. For my purposes, I just compiled everything to `js`, a sibling of `src`, and changed `index.js` to match.

**Comment by tmcw** [comment]
Getting the same issue, unfortunately. It's not clear if there' really a simple solution to this - I've tried coffeeify at the octokat level and at my module's level. If there's a PR way you know of to make coffeescript work with the grain, happy to write it, but otherwise I'm probably building a dist rather than trying to use octokat via npm.
