### ISSUE TITLE
Cannot get Projects - is the Projects API implemented?

### ISSUE THREAD

**Issue by petrpacas** [philschatz/octokat.js#144]
More info here:
http://stackoverflow.com/questions/42836937/github-api-octokat-js-cannot-get-projects

**Comment by philschatz** [comment]
Dekuji za odeslani tohoto problemu!

The project API has not been added yet (maybe because it is a Preview API). If you were interested in adding it by submitting a Pull Request, it would require adding entries to these 3 files:

- [tree-options.js](https://github.com/philschatz/octokat.js/blob/master/src/grammar/tree-options.js) which allows you to type the `.projects` part of `repo.projects.fetchAll()`
- [url-validator.coffee](https://github.com/philschatz/octokat.js/blob/master/src/grammar/url-validator.coffee) validates the URL before making the request
- [preview-headers.coffee](https://github.com/philschatz/octokat.js/blob/master/src/grammar/preview-headers.coffee) sends the proper preview header (`application/vnd.github.inertia-preview+json`) based on when the URL matches a certain regular expression

It seems that to fully implement the [Project API](https://developer.github.com/v3/projects/) these URLs would need to be matched in the 3 files listed above:

- `/projects/:id`
- `/orgs/:org/projects`
- `/repos/:owner/:repo/projects`

**Comment by petrpacas** [comment]
Haha, now you got me confused: Are you Czech? 🤔 

Anyway, there's also [columns](https://developer.github.com/v3/projects/columns/) and [cards](https://developer.github.com/v3/projects/cards/) that'd need to be implemented.
