### ISSUE TITLE
Error with parsed json returned by gists

### ISSUE THREAD

**Issue by gmaclennan** [philschatz/octokat.js#29]
`octo.gists(gist_id).fetch()` returns incorrectly parsed json for `data.files`:

```js
{
raw: 
      { [Function]
        url: 'https://gist.githubusercontent.com/..../file.txt' },
}
```

This should be `raw_url` but it looks like somehow it is getting parsed. `read()` returns the correct unparsed json string.

**Comment by gmaclennan** [comment]
Here's a failing test:

https://github.com/gmaclennan/octokat.js/blob/gist-raw_url-test/test/ruby-specs/gists.spec.coffee#L112

Sorry I don't really know chai, but raw_url should be a url, but it is undefined.

**Comment by philschatz** [comment]
Thanks! You should be able to use `raw.url` instead of `raw_url`. This conversion is a result of adding support for [GitHub's Hypermedia](https://developer.github.com/v3/#hypermedia) (details in the [Repo Readme](https://github.com/philschatz/octokat.js#hypermedia)).

There should probably be an option for turning off the JSON conversion in future versions of this client.

**Comment by gmaclennan** [comment]
Aha! I had missed that part of the readme. It makes sense now.
