### ISSUE TITLE
Understanding callbacks on `repo.contents().add()`

### ISSUE THREAD

**Issue by gmaclennan** [philschatz/octokat.js#30]
When I am using the callback pattern for creating a new file, what arguments should I expect to get on the callback?

When I try to add a file to an invalid repo with:

```js
octo.repo('myuser', 'nonexistentrepo').contents('myfile.txt').add(function (err, info) {
 // err is undefined
})
```

**Comment by philschatz** [comment]
That might be a bug. Could you try adding:

```coffee
replace      : (cb, config) ->   URL_TESTER(_path); request('PUT', _path, config, {}, cb)
```

to https://github.com/philschatz/octokat.js/blob/master/src/chainer.coffee#L44 and use it instead of `.add` (which yields a boolean)

**Comment by philschatz** [comment]
The current semantics for `.add(cb)` are `(err, bool) ->` where `bool = true` if the "add" was successful (HTTP 20x status) and `bool = false` (HTTP 40x status) when the "add" was unsuccessful (since it is usually a boolean request).

Alternatively, I could set the `err` depending on the HTTP status code. However, if the HTTP status is 404, the result would be `(null, false)` which may be confusing.

**Comment by gmaclennan** [comment]
Thanks, this clarifies things. It's a little confusing in the code using the boolean rather than the error to check for an error (404) but it works, for now. Would be great to update docs or find a way of simplifying this. For now I can use this info to get things working correctly.
