### ISSUE TITLE
issue property names don't match github API docs

### ISSUE THREAD

**Issue by sam-github** [philschatz/octokat.js#82]
I just got bit by something I mentioned in https://github.com/philschatz/octokat.js/issues/75#issuecomment-156781928, and want to raise it as an issue.

octokat.js follows the github API very closely, many thumbs up, but it renames all the properties from snake case to camel case.... I just tried to filter out pull requests as stated in https://developer.github.com/v3/issues/#list-issues-for-a-repository, looking for the presence of `pull_request`, it didn't work. poked around a bit, saw it was called `pullRequest`...

Renaming seems idiosyncratic, like the github API naming or not, its still its API, and renaming things can be done in user code, if they want.

**Comment by philschatz** [comment]
Ah, yes it does that by default in order to be JavaScript-friendly (originally from this blog post: [What makes a good API wrapper?](http://wynnnetherland.com/journal/what-makes-a-good-api-wrapper/) but it introduces significant overhead, not to mention confusion.

#81 aims to fix this by allowing people to choose which features they want enabled in Octokat via plugins (similar to how `lodash` is organized). If that helps, please feel free to try it out or comment on #81 !

Closing for now but feel free to reopen if this did not help :smile:
